pipeline {
    agent {
        docker {
            image 'node:6-alpine'
            args '-p 3000:3000 -p 5000:5000'
        }
    }
    environment {
        CI = 'true'
    }


    stages {

    stage('Checkout code') {
            steps {
                checkout scm
            }
        }

        stage('Build') {
            steps {
                sh 'npm install'
            }
        }
        stage('Test') {
            steps {
                sh './scripts/test.sh'
            }
        }

        stage('Deliver for deployment') {
            steps {
                sh './scripts/deploy.sh'
            }
        }
 stage('Cleanup'){

          echo 'prune and cleanup'
          sh 'npm prune'
          sh 'rm node_modules -rf'

          mail body: 'project build successful',
                      from: 'xxxx@yyyyy.com',
                      replyTo: 'xxxx@yyyy.com',
                      subject: 'project build successful',
                      to: 'yyyyy@yyyy.com'
        }
    }

    post {
            success {
              githubNotify gitApiUrl: 'https://github.com/bhagirathcloud/SRAssesment.git', context: 'something test', description: 'It works',  status: 'SUCCESS'
            }
            failure {
              githubNotify gitApiUrl: 'https://github.com/bhagirathcloud/SRAssesment.git', context: 'something test', description: 'This commit cannot be built',  status: 'FAILED'
            }
        }
}